src/panel_material_ui/widgets/ButtonGroup.jsx
src/panel_material_ui/widgets/select.py
tests/ui/widgets/test_select.py

Fixes https://github.com/panel-extensions/panel-material-ui/issues/22
There're 2 components that uses ButtonGroup, the `RadioButtonGroup` and `CheckButtonGroup` widgets. How they called (Button Group related) is a bit different from the corresponding Material UI component (Toggle Button) so it could be a bit confusing. 
This MR:
- remove `variant` as it is not present in Material UI Toggle Button
- apply `size` and `color` to the buttons / options
- update test accordingly

ButtonGroup formatting fixes

---

src/panel_material_ui/widgets/Button.jsx
src/panel_material_ui/widgets/button.py

Fixes some issues related to description/tooltip renaming and implements `description_delay`.

Implement Button description and description_delay

---

src/panel_material_ui/widgets/PasswordField.jsx
src/panel_material_ui/widgets/TextArea.jsx
src/panel_material_ui/widgets/TextField.jsx

Render `placeholder` for PasswordField, TextArea and TextField

Render placeholder for input widgets

---

src/panel_material_ui/widgets/Autocomplete.jsx
src/panel_material_ui/widgets/select.py
tests/ui/widgets/test_select.py

Implements `AutocompleteInput` features: `min_characters`, `search_strategy` and `restrict`.

Implement AutocompleteInput filtering options

---

src/panel_material_ui/widgets/indicators.py

Fixes https://github.com/panel-extensions/panel-material-ui/issues/44

LoadingIndicator: remove unused params

---

src/panel_material_ui/layout/Divider.jsx
tests/ui/layout/test_layout.py

Fixes https://github.com/panel-extensions/panel-material-ui/issues/46

Divider: only show non empty objects

---

src/panel_material_ui/widgets/TimePicker.jsx
src/panel_material_ui/widgets/input.py
tests/ui/widgets/test_time_picker.py

There were issues instantiating the time picker with the input value, and also a lot of unconnected params. Also, some outdated params (like flatpickr).
```python
import panel as pn
from datetime import time
from panel_material_ui import *
pn.extension(template='material')
tp = TimePicker(
value="11:59",
)
def print_time_picker_value(event):
print(tp.value)
pn.bind(print_time_picker_value, tp.param.value, watch=True)
button = pn.widgets.Button(name='Print TimePicker Value')
button.on_click(print_time_picker_value)
pn.Column(tp, button).show()
```

Fix time picker

---

src/panel_material_ui/widgets/DateTimePicker.jsx
src/panel_material_ui/widgets/input.py
tests/ui/widgets/test_datetime_picker.py

Edit: there's still an issue with DatetimePicker and DateRangePicker, but I think this PR is getting too large already so I'll fix in another PR.
Semi closes https://github.com/panel-extensions/panel-material-ui/issues/59
There was a disconnect between DatetimePicker's Python value and the value shown on the frontend--it wasn't showing the time and it wasn't completely synced. However, there seems to be an issue with DatePicker after these changes.
```python
import panel as pn
from datetime import time
from panel_material_ui import *
pn.extension(template='material')
tp = DatetimePicker(
value=datetime(2023, 10, 1, 12, 30),
)
def print_time_picker_value(event):
print(tp.value)
pn.bind(print_time_picker_value, tp.param.value, watch=True)
button = pn.widgets.Button(name='Print TimePicker …
```

Fix datetime picker

---

pyproject.toml

We attempted to install panel-material-ui from source with @thuydotm running `pip install -e .`, the build pulled an incompatible version of Panel.

build: fix panel pin

---

examples/components.py
src/panel_material_ui/utils.js

Previously it was both cumbersome and expensive to set a `theme_config` on every single element you wanted to style. 
- Cumbersome because the config has to be passed along **everywhere** or set on the type itself
- Expensive because if you had a complex `theme_config` that would be sent for every single component
This PR instead makes every component search its parents for a component that was themed and then inherits that theme. If you override the theme on the component itself that will revert it.
Since observing every parent is potentially quite expensive, once mounted, you either inherit the theme from the parent that was themed at mount or from yourself. If an intermediate parent is themed after initial mount that theme will not automatically flow down.

Add theme inheritance

---

DEVELOPER_GUIDE.md
doc/customization/color.md
doc/customization/index.md
doc/customization/palette.md
doc/customization/typography.md

Partly Addresses
- #133: By improving the Developer Guide
- #132: By changing package name from `panel_material_ui` to `panel-material-ui`. I would really like to change it. 1) Because dash is Python convention 2) Because I want to use name with dash when promoting the package.

Review feedback

---

examples/reference/layouts/Drawer.ipynb
src/panel_material_ui/layout/Drawer.jsx
src/panel_material_ui/layout/base.py

Useful for building sidebars and context menus.

Add Drawer layout

---

src/panel_material_ui/__init__.py

This was leaking a bunch of imports into the global namespace

Do no export all contents of notification module

---

doc/customization/customize.md
doc/customization/dark_mode.md
examples/components.py
src/panel_material_ui/_templates/base.html
src/panel_material_ui/pane/Typography.jsx
src/panel_material_ui/param.py
src/panel_material_ui/template/Page.jsx
src/panel_material_ui/template/ThemeToggle.jsx
src/panel_material_ui/template/base.py
src/panel_material_ui/utils.js
src/panel_material_ui/widgets/Breadcrumbs.jsx

This PR does a few things:
- Add `.mui-dark` or `.mui-light` class to containers to make it possible to write themed `sx` selectors
- Allow providing separate `theme_config` for dark and light modes.
- Add `ThemeToggle` which allows globally managing theming
- Change `theme_config` inheritance ensuring it inherits all `theme_config` in the parent tree.

Refactor theme inheritance and add standalone ThemeToggle

---

src/panel_material_ui/base.py
src/panel_material_ui/layout/Backdrop.jsx
src/panel_material_ui/layout/Box.jsx
src/panel_material_ui/layout/Card.jsx
src/panel_material_ui/layout/Container.jsx
src/panel_material_ui/layout/Dialog.jsx
src/panel_material_ui/layout/Drawer.jsx
src/panel_material_ui/layout/Grid.jsx
src/panel_material_ui/layout/Paper.jsx
src/panel_material_ui/layout/base.py
src/panel_material_ui/template/base.py
src/panel_material_ui/utils.js
src/panel_material_ui/widgets/input.py

- Add `Row`/`Column` layouts
- Apply flex handling to ensure layouts behave like Bokeh
- Ensure serving or saving Material components enable theme management
Fixes https://github.com/panel-extensions/panel-material-ui/issues/193

Add flex layouts and handling and improve managed theme

---

examples/reference/layouts/Drawer.ipynb
src/panel_material_ui/NotificationArea.jsx
src/panel_material_ui/layout/Drawer.jsx
src/panel_material_ui/layout/base.py
src/panel_material_ui/notifications.py
src/panel_material_ui/template/ThemeToggle.jsx
src/panel_material_ui/template/base.py
src/panel_material_ui/utils.js
src/panel_material_ui/widgets/icon.py
tests/ui/test_notifications.py

- Enables deep theme inheritance, i.e. each component watches for `theme_config` changes on all its MaterialUI parents and then deepmerges the theme configurations
- Fix `value` handling and `switch` variant on `ThemeToggle` (https://github.com/panel-extensions/panel-material-ui/issues/194, https://github.com/panel-extensions/panel-material-ui/issues/192)
- Fix flaky Notification test

Enable deep theme inheritance

---

src/panel_material_ui/layout/base.py

Fixes https://github.com/panel-extensions/panel-material-ui/issues/189

Ensure temporary Drawer does not take up space

---

examples/reference/widgets/Button.ipynb
src/panel_material_ui/widgets/Button.jsx
src/panel_material_ui/widgets/base.py
src/panel_material_ui/widgets/button.py

I test out all the amazing fixes and

Button Follow Up Review

---

examples/reference/layouts/Dialog.ipynb
src/panel_material_ui/layout/Dialog.jsx
src/panel_material_ui/layout/base.py

`Dialog.close_on_click` makes it possible to close the Dialog when clicking outside the dialog area.

Add Dialog.close_on_click

---

doc/index.md

I noticed that the `conda install` points to a package that doesn't exist. It should be `panel-material-ui`.

Fix conda install instructions

---

src/panel_material_ui/template/Page.jsx
src/panel_material_ui/utils.js

- Theme overrides did not correctly override defaults.
- Theme config on parents was not being correctly watched
- The default primary dark color did not look good in the header so we override it by default

Correctly resolve themes and set default primary color

---

examples/reference/widgets/Switch.ipynb

Update Switch.ipynb to mention it is interchangeable not only with Toggle, but also with the Checkbox widget.
Updated the text to reflect this.
The Switch doc does not yet contain a References section at the bottom of the doc.
Note: the Checkbox doc does not yet mention it is interchangeable with both the other 2 widgets. Neither does the doc for Toggle.
See also https://github.com/holoviz/panel/pull/7761

Update Switch.ipynb to mention it is interchangeable not only with Toggle, but also with Checkbox

---

examples/reference/widgets/Button.ipynb

Read through the doc.
Changed section name API to API Reference so it aligns with other docs.
Regarding the current sentence:
For compatibility with Panel certain parameters are allowed as aliases:
should that be i.e.:
For compatibility with the API of Panel 1.x, certain parameters are allowed as aliases:

Update Button.ipynb to change section name and minor textual change

---

src/panel_material_ui/layout/Card.jsx
src/panel_material_ui/layout/base.py
tests/ui/layout/test_card.py

Closing #347 
```python
import panel as pn
import panel_material_ui as pmui
pn.extension()
objects_list = [None, "Card Content"]
headers_list = [None, "Header"]
collapsibles_list = [True, False]
cards = []
for obj in objects_list:
for header in headers_list:
for collapsible in collapsibles_list:
label = f"object={'None' if obj is None else 'Card Content'}, header={'None' if header is None else 'Header'}, collapsible={collapsible}"
card_kwargs = {}
if obj is not None:
card_kwargs["objects"] = [obj]
if header is not None:
card_kwargs["header"] = header
card_kwargs["collapsible"] = collapsible
cards.append(pmui.Column(f"### {label}", pmui.Card(**card_kwargs)))
pmui.Column(
"# Card Combinations Demo",
*cards
).servable()
```

fix card collapsed

---

pixi.toml

Closing #289 
I don't know if more more feature tasks should be listed as tasks? At least know the tasks mentioned in DEVELOPER_GUIDE works.
(✔ pixi is already up-to-date (version 0.49.0))
The changes you just pushed fix #289 because:
The problem was that pixi run compile-dev was not available, even though it was listed as a task.
This happened because compile-dev was only defined under a feature section ([feature.compile-task.tasks]), which requires activating a specific environment or feature—something that was not set up or documented for users.
By moving compile-dev (and related tasks) to the top-level [tasks] section in [pixi.toml](vscode-file://vscode-app/c:/Users/masma/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html), …

expose compile-dev

---

examples/reference/widgets/TextInput.ipynb
src/panel_material_ui/widgets/Slider.jsx

Otherwise there's often no space for the editable fields.

Wrap EditableSlider label

---

doc/how_to/icons.md

Did another read-through of the docs in the How-To section @philippjfr and @MarcSkovMadsen . Found 2 small issues, 1 in icons.md and 1 in components.md.
Why are the How-To docs .md Markdown, and not .ipynb Notebooks, like the docs in the widget gallery?
Made PR's for both issues.
This PR fixes a textual issue in the first sentence of the icon doc.

Fix textual issue in icons.md

---

doc/how_to/components.md

Changed "MUI documentation" text to a hyperlink to the MUI documentation: https://mui.com/material-ui/all-components/

Add link in components.md doc

---

src/panel_material_ui/layout/Tabs.jsx

Empty tabs were still taking up space, we therefore set `display: none` if there's no children.

Hide empty Tabs

---

src/panel_material_ui/chat/ChatStep.jsx
src/panel_material_ui/layout/Card.jsx

They were overflowing, which is never desirable.

Ensure Card and ChatStep titles wrap

---

src/panel_material_ui/description.jsx

Partial fix for https://github.com/panel-extensions/panel-material-ui/issues/400

Switch to outlined info icon for description

---

src/panel_material_ui/widgets/Select.jsx

Before:
After:
If all options are chosen:
Now, the MultiChoice widget as adapted here behaves just like the [original panel widget](https://panel.holoviz.org/reference/widgets/MultiChoice.html), which I'd say is more user friendly.  Changes here don't affect other widgets like Select or MultiSelect.

Hide selected options in MultiChoice option list

---

src/panel_material_ui/chat/ChatArea.jsx
src/panel_material_ui/chat/input.py

Builds on https://github.com/panel-extensions/panel-material-ui/pull/440
Allows adding arbitrary widgets to the footer of the ChatAreaInput

Add `footer_objects` to ChatAreaInput

---

src/panel_material_ui/widgets/IconButton.jsx
src/panel_material_ui/widgets/ToggleIcon.jsx

You couldn't provide a CSS size for the icons before.

Ensure CSS icon_size is permitted on IconButton and ToggleIcon

---

pixi.toml
pyproject.toml
src/panel_material_ui/pane/base.py
src/panel_material_ui/template/__init__.py
src/panel_material_ui/template/base.py

- Registers default widget overrides for `HoloViews` pane
- Register `mui` as a supported template for `pn.config.template`
- Bumps required panel version

Register HoloViews widgets and template
