- pixi.toml
- pyproject.toml
Configure `test-ui` similar to `panel`
> Config test-ui with playwright

- src/panel_material_ui/widgets/sliders.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/14
> Rating: remove unused params

- src/panel_material_ui/widgets/select.py
- tests/widgets/test_select.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/17
> Ensure AutocompleteInput can be set to None

- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/sliders.py
- tests/ui/widgets/test_sliders.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/13
> Ensure vertical sliders render correctly

- src/panel_material_ui/widgets/Rating.jsx
- src/panel_material_ui/widgets/sliders.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/16
> Ensure Rating can be zero

- src/panel_material_ui/widgets/IconButton.jsx
- src/panel_material_ui/widgets/ToggleButton.jsx
- src/panel_material_ui/widgets/button.py
Closes https://github.com/panel-extensions/panel-material-ui/issues/5
> Implement description delay for ButtonIcon and Toggle

- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/sliders.py
- tests/ui/widgets/test_sliders.py
Implements support for providing bokeh tick formatters to Slider widgets.
> Implement Slider.format

- src/panel_material_ui/base.py
Implements theming at the baseclass level by wrapping the component implementation and wrapping it in a `ThemeProvider`.
> Implement theming

- src/panel_material_ui/chat/ChatArea.jsx
- src/panel_material_ui/chat/__init__.py
- src/panel_material_ui/chat/input.py
- src/panel_material_ui/widgets/TextArea.jsx
- src/panel_material_ui/widgets/TextField.jsx
- src/panel_material_ui/widgets/input.py
- tests/ui/widgets/test_input.py
> Implement ChatAreaInput

- src/panel_material_ui/widgets/Autocomplete.jsx
- src/panel_material_ui/widgets/ButtonGroup.jsx
- src/panel_material_ui/widgets/RadioGroup.jsx
- src/panel_material_ui/widgets/Select.jsx
- src/panel_material_ui/widgets/select.py
- tests/ui/widgets/test_select.py
> Select widgets: add missing features

- .github/workflows/test.yaml
- pixi.toml
Align CI configuration with Panel and other HoloViz projects.
> Align CI configuration

- src/panel_material_ui/widgets/sliders.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/58
> Allow setting IntSlider.step

- pixi.toml
- pyproject.toml
- src/panel_material_ui/base.py
- src/panel_material_ui/theme.py
- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/ToggleButton.jsx
- src/panel_material_ui/widgets/button.py
Factors out some utilities for controlling the theme and implements a shared singleton which switches the theme across components.
> Add global control over theme

- src/panel_material_ui/layout/Card.jsx
- src/panel_material_ui/layout/Tabs.jsx
- src/panel_material_ui/layout/base.py
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
Various fixes and improvements for layout sizing
> Fix and improve layout components

- src/panel_material_ui/base.py
- src/panel_material_ui/utils.js
Theming was broken when no `theme_config` was provided.
> Fix theming if no theme_config provided

- src/panel_material_ui/widgets/NumberInput.jsx
- src/panel_material_ui/widgets/input.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/86
Fixes https://github.com/panel-extensions/panel-material-ui/issues/81
Supersedes https://github.com/panel-extensions/panel-material-ui/pull/87
> Reimplement NumberInput widgets

- src/panel_material_ui/widgets/FileInput.jsx
- src/panel_material_ui/widgets/input.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/38
Fixes https://github.com/panel-extensions/panel-material-ui/issues/80
> Fix and improve FileInput

- pixi.toml
- pyproject.toml
- src/panel_material_ui/__init__.py
- src/panel_material_ui/base.py
- src/panel_material_ui/chat/ChatArea.jsx
- src/panel_material_ui/chat/ChatMessage.jsx
- src/panel_material_ui/chat/ChatStep.jsx
- src/panel_material_ui/chat/__init__.py
- src/panel_material_ui/chat/feed.py
- src/panel_material_ui/chat/input.py
- src/panel_material_ui/chat/interface.py
- src/panel_material_ui/chat/message.py
- src/panel_material_ui/chat/step.py
- src/panel_material_ui/layout/Accordion.jsx
- src/panel_material_ui/layout/Alert.jsx
- src/panel_material_ui/layout/Backdrop.jsx
- src/panel_material_ui/layout/Card.jsx
- src/panel_material_ui/layout/Tabs.jsx
- src/panel_material_ui/layout/base.py
- src/panel_material_ui/notifications.py
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/utils.js
> Implement Chat Components

- src/panel_material_ui/widgets/Select.jsx
- src/panel_material_ui/widgets/select.py
Closes https://github.com/panel-extensions/panel-material-ui/issues/21
> Minor cleanup of Select widgets

- src/panel_material_ui/_templates/base.html
- src/panel_material_ui/base.py
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/ButtonGroup.jsx
- `Page` component now loads a custom template which defines high-level variables
- If we are in a `Page` then CSS variables are injected into the global DOM and dark theme is globally linked
- If we are in a standalone context then theming is performed on a per-component basis
> Unify theme handling

- src/panel_material_ui/__init__.py
- src/panel_material_ui/param.py
Swap Param widget implementations with Panel versions.
> Add Param patches

- doc/customization/color.md
- doc/customization/customize.md
- doc/customization/dark_mode.md
- doc/customization/index.md
- doc/customization/palette.md
- doc/customization/typography.md
- doc/index.md
- examples/reference/layouts/Accordion.ipynb
- examples/reference/widgets/Button.ipynb
- examples/reference/widgets/FileDownload.ipynb
- src/panel_material_ui/pane/Typography.jsx
- src/panel_material_ui/pane/base.py
Initial cut of some docs covering how to customize styling and theming.
> Add customization guides

- src/panel_material_ui/widgets/Autocomplete.jsx
- src/panel_material_ui/widgets/BoxGroup.jsx
- src/panel_material_ui/widgets/Button.jsx
- src/panel_material_ui/widgets/ButtonGroup.jsx
- src/panel_material_ui/widgets/ColorPicker.jsx
- src/panel_material_ui/widgets/DateTimePicker.jsx
- src/panel_material_ui/widgets/FileInput.jsx
- src/panel_material_ui/widgets/MultiSelect.jsx
- src/panel_material_ui/widgets/NumberInput.jsx
- src/panel_material_ui/widgets/PasswordField.jsx
- src/panel_material_ui/widgets/RadioGroup.jsx
- src/panel_material_ui/widgets/Select.jsx
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/TextArea.jsx
- src/panel_material_ui/widgets/TextField.jsx
- src/panel_material_ui/widgets/TimePicker.jsx
- src/panel_material_ui/widgets/ToggleButton.jsx
- tests/ui/widgets/test_sliders.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/139
> Consistently handle Widget labels and width

- src/panel_material_ui/_templates/base.html
- src/panel_material_ui/template/base.py
- src/panel_material_ui/theme.py
Correctly load design and theme resources.
> Improve handling of theme resources

- doc/conf.py
- examples/reference/menus/Breadcrumbs.ipynb
- examples/reference/menus/List.ipynb
- examples/reference/menus/MenuButton.ipynb
- examples/reference/menus/Pagination.ipynb
- examples/reference/menus/SpeedDial.ipynb
- pixi.toml
- pyproject.toml
- src/panel_material_ui/widgets/Breadcrumbs.jsx
- src/panel_material_ui/widgets/ButtonGroup.jsx
- src/panel_material_ui/widgets/Fab.jsx
- src/panel_material_ui/widgets/List.jsx
- src/panel_material_ui/widgets/MenuButton.jsx
- src/panel_material_ui/widgets/Pagination.jsx
- src/panel_material_ui/widgets/SpeedDial.jsx
- src/panel_material_ui/widgets/button.py
- src/panel_material_ui/widgets/menus.py
Review of menu components along with various fixes and documentation.
> Clean up and document Menus

- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/utils.js
The theme handling was triggering many unnecessary re-renders, which is fixed here.
> Ensure no race conditions and multiple rerenders on theme changes

- src/panel_material_ui/_templates/base.html
- src/panel_material_ui/template/base.py
- src/panel_material_ui/theme.py
- Use the base template **always**
- Ensure the base theming variables are applied
Fixes https://github.com/panel-extensions/panel-material-ui/issues/166
> Align theming and ensure variables are set

- doc/conf.py
- examples/reference/page/Page.ipynb
- src/panel_material_ui/base.py
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
Review and cleanup of Page, providing clean ways to style it and documenting it nicely with previews.
Closes https://github.com/panel-extensions/panel-material-ui/issues/138
> Improve and document Page

- src/panel_material_ui/utils.js
Further simplification for https://github.com/panel-extensions/panel-material-ui/pull/191
> Style tooltips

- src/panel_material_ui/base.py
- src/panel_material_ui/utils.js
- Add Roboto
- Clean up Material UI icons that are included
> Font handling

- doc/customization/icons.md
- doc/customization/index.md
- src/panel_material_ui/base.py
- src/panel_material_ui/theme.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/151
> Document icon usage

- doc/_scripts/demo.py
- examples/reference/page/BreakpointSwitcher.ipynb
- examples/reference/page/Manual.ipynb
- src/panel_material_ui/template/BreakpointSwitcher.jsx
- src/panel_material_ui/template/base.py
Allows switching between two components depending on a `breakpoint` or `media_query`.
> Add BreakpointSwitcher

- src/panel_material_ui/base.py
- src/panel_material_ui/chat/feed.py
- src/panel_material_ui/chat/input.py
- src/panel_material_ui/chat/interface.py
- src/panel_material_ui/chat/message.py
- src/panel_material_ui/chat/step.py
- src/panel_material_ui/layout/base.py
- src/panel_material_ui/pane/base.py
- src/panel_material_ui/template/base.py
- src/panel_material_ui/widgets/button.py
- src/panel_material_ui/widgets/icon.py
- src/panel_material_ui/widgets/indicators.py
- src/panel_material_ui/widgets/input.py
- src/panel_material_ui/widgets/menus.py
- src/panel_material_ui/widgets/misc.py
- src/panel_material_ui/widgets/select.py
- src/panel_material_ui/widgets/slider.py
I will go systematically through the docstrings of the components to make sure the reference link to panel-material-ui is there. I will also fix other links or examples if I find issues.
> Docstring reference improvements

- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/utils.js
Fixes https://github.com/panel-extensions/panel-material-ui/issues/227
> Ensure theme_config can toggle between dark and light themes

- examples/reference/page/Page.ipynb
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
Implements https://github.com/panel-extensions/panel-material-ui/issues/223
Fixes https://github.com/panel-extensions/panel-material-ui/issues/226
> Add busy indicator to Page

- src/panel_material_ui/_templates/base.html
- src/panel_material_ui/_utils.py
- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
- tests/test_templates.py
Matching the behaviors of templates.
Fixes https://github.com/panel-extensions/panel-material-ui/issues/222
Fixes https://github.com/panel-extensions/panel-material-ui/issues/221
> Allow Page to render local icons and logos

- examples/reference/widgets/DiscreteSlider.ipynb
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/slider.py
This reviews the `DiscreteSlider`.
Overall I don't understand why this is implemented as a `CompositeWidget`. Makes it much harder to understand how it works and contribute to improvements.
Looks like the "normal" track
Should support values `on`, `off` and `auto` values. Parameter is bool though.
> DiscreteSlider Review

- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/Select.jsx
Fixes https://github.com/panel-extensions/panel-material-ui/issues/233
> Ensure Select menu is correctly positioned in notebook

- src/panel_material_ui/_utils.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/248
> Fix embedding of ico files on favicon

- src/panel_material_ui/utils.js
Ensure theming does not error out should a `view` lookup fail.
> Make theming robust to failed view lookups

- src/panel_material_ui/template/Page.jsx
Ensures that components added to header, sidebar and contextbar on `Page` size according to Bokeh flex rules.
> Ensure components in Page follow flex sizing

- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/NumberInput.jsx
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/slider.py
Editable sliders were the only component left not implemented properly on the JS side.
> Reimplement editable sliders in React

- examples/reference/layouts/FlexBox.ipynb
- src/panel_material_ui/layout/Box.jsx
- src/panel_material_ui/layout/base.py
Adds another missing element type.
> Add FlexBox layout

- src/panel_material_ui/widgets/IconButton.jsx
- src/panel_material_ui/widgets/ToggleIcon.jsx
- src/panel_material_ui/widgets/icon.py
Allow both to accept "small", "medium", "large" and custom sizes.
> Align IconButton and ToggleIcon sizing

- src/panel_material_ui/layout/Card.jsx
Adjust some padding values on Card
> Card padding tweaks

- src/panel_material_ui/template/Page.jsx
- src/panel_material_ui/template/base.py
Better alignment with Panel Template
> Add Page.site_url option

- doc/customization/customize.md
- src/panel_material_ui/base.py
- src/panel_material_ui/layout/base.py
- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/input.py
- src/panel_material_ui/widgets/menus.py
- src/panel_material_ui/widgets/select.py
Standardize on primary color across all components along with some other minor tweaks.
> Standardize on primary color in theme

- src/panel_material_ui/widgets/slider.py
> Set Slider color to primary

- src/panel_material_ui/template/Page.jsx
Fixes https://github.com/panel-extensions/panel-material-ui/issues/274
> Correctly determine sizing_mode on Page

- src/panel_material_ui/base.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/277
> Embed iframe content using srcdoc attribute for compatibility

- examples/reference/widgets/AutocompleteInput.ipynb
- examples/reference/widgets/Button.ipynb
- src/panel_material_ui/widgets/Autocomplete.jsx
- src/panel_material_ui/widgets/select.py
- tests/ui/widgets/test_select.py
- tests/widgets/test_select.py
Review of the AutocompleteInput.
> Review AutocompleteInput

- examples/reference/widgets/Checkbox.ipynb
- src/panel_material_ui/widgets/Checkbox.jsx
- src/panel_material_ui/widgets/input.py
- tests/ui/widgets/test_input.py
> Review Checkbox

- .github/workflows/test.yaml
- src/panel_material_ui/widgets/ColorPicker.jsx
- src/panel_material_ui/widgets/Fab.jsx
- src/panel_material_ui/widgets/button.py
- tests/ui/test_autocomplete_input.py
- tests/ui/widgets/test_button.py
- tests/ui/widgets/test_check_button_group.py
- tests/ui/widgets/test_checkbox.py
- tests/ui/widgets/test_color_picker.py
- tests/ui/widgets/test_date_picker.py
- tests/ui/widgets/test_fab.py
- tests/ui/widgets/test_file_input.py
- tests/ui/widgets/test_icon.py
- tests/ui/widgets/test_input.py
- tests/ui/widgets/test_radio_box_group.py
- tests/ui/widgets/test_radio_button_group.py
- tests/ui/widgets/test_select.py
- tests/ui/widgets/test_switch.py
- tests/ui/widgets/test_text_area.py
Attempt at getting test coverage to be decent.
> Reorganize and add tests

- examples/reference/widgets/EditableIntRangeSlider.ipynb
- examples/reference/widgets/EditableRangeSlider.ipynb
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/slider.py
- tests/ui/widgets/test_editable_range_slider.py
> Implement EditableRangeSliders

- src/panel_material_ui/widgets/MenuButton.jsx
- src/panel_material_ui/widgets/menus.py
- tests/ui/widgets/test_menu_button.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/280
> Support href and target on MenuButton

- doc/how_to/customize.md
- examples/reference/page/BreakpointSwitcher.ipynb
- examples/reference/page/ThemeToggle.ipynb
Fixes https://github.com/panel-extensions/panel-material-ui/issues/272
> Add ThemeToggle reference page

- examples/reference/indicators/LoadingSpinner.ipynb
- examples/reference/indicators/Progress.ipynb
- src/panel_material_ui/widgets/CircularProgress.jsx
> Review Indicators

- examples/reference/widgets/AutocompleteInput.ipynb
- examples/reference/widgets/PasswordInput.ipynb
- examples/reference/widgets/TextInput.ipynb
- src/panel_material_ui/widgets/Autocomplete.jsx
- src/panel_material_ui/widgets/PasswordField.jsx
- src/panel_material_ui/widgets/TextField.jsx
- src/panel_material_ui/widgets/input.py
- src/panel_material_ui/widgets/select.py
> Align TextInput, PasswordInput and AutocompleteInput

- src/panel_material_ui/template/Page.jsx
- tests/ui/template/test_page.py
Fix issue https://github.com/panel-extensions/panel-material-ui/pull/328
> Fix Page header_color

- src/panel_material_ui/_templates/base.html
- src/panel_material_ui/template/base.py
- tests/test_templates.py
- Fixes `Page.meta.title`
- Avoids random `Page.meta.name`
> Improve handling of Page.meta

- examples/reference/widgets/DatetimePicker.ipynb
- examples/reference/widgets/TimePicker.ipynb
- src/panel_material_ui/widgets/TimePicker.jsx
- src/panel_material_ui/widgets/input.py
Reviews the `TimePicker` reference notebook and fixes issues discovered.
> Review TimePicker

- doc/_scripts/demo.py
- examples/components.py
- examples/reference/menus/MenuList.ipynb
- src/panel_material_ui/widgets/menus.py
- tests/ui/widgets/test_menu_list.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/306
> Rename List to MenuList

- examples/reference/layouts/Container.ipynb
- src/panel_material_ui/layout/Container.jsx
- src/panel_material_ui/layout/base.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/330
> Review Container reference

- src/panel_material_ui/pane/Typography.jsx
- src/panel_material_ui/pane/base.py
This PR adds what I see LLMs trying to use
> Give LLMs what they expect

- src/panel_material_ui/pane/Typography.jsx
- src/panel_material_ui/pane/base.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/348
> Fix updates to Typography pane

- doc/conf.py
- examples/reference/panes/Avatar.ipynb
- examples/reference/panes/Chip.ipynb
- examples/reference/panes/Skeleton.ipynb
- examples/reference/widgets/Button.ipynb
- src/panel_material_ui/pane/Avatar.jsx
- src/panel_material_ui/pane/Chip.jsx
- src/panel_material_ui/pane/Skeleton.jsx
- src/panel_material_ui/pane/base.py
- tests/panes/test_panes.py
I can see its not only about adding reference guides. Its actually about making the implementations work too.
> Add pane reference guides

- src/panel_material_ui/chat/ChatArea.jsx
- src/panel_material_ui/chat/input.py
- src/panel_material_ui/chat/interface.py
- src/panel_material_ui/utils.js
- src/panel_material_ui/widgets/FileInput.jsx
- src/panel_material_ui/widgets/_mime.py
- src/panel_material_ui/widgets/input.py
- tests/widgets/test_fileinput.py
Factors out a baseclass to handle file uploads and then implements file upload handling on ChatAreaInput including rendering of chips to preview the uploaded files.
> Implement file upload on ChatAreaInput

- src/panel_material_ui/chat/ChatArea.jsx
Fixes autogrow of `ChatAreaInput` and tweaks layout.
> Enhance ChatAreaInput

- examples/reference/layouts/Backdrop.ipynb
> Update Backdrop.ipynb text

- src/panel_material_ui/theme.py
- src/panel_material_ui/utils.js
Fixes https://github.com/panel-extensions/panel-material-ui/issues/407
> Ensure classic panel components are styled correctly

- src/panel_material_ui/NotificationArea.jsx
- src/panel_material_ui/notifications.py
Fixes https://github.com/panel-extensions/panel-material-ui/issues/402
> Handle sync of MuiNotification model

- src/panel_material_ui/chat/ChatMessage.jsx
Fixes https://github.com/panel-extensions/panel-material-ui/issues/416
> Change ChatMessage placeholder loading animation

- src/panel_material_ui/description.jsx
- src/panel_material_ui/widgets/Autocomplete.jsx
- src/panel_material_ui/widgets/ButtonGroup.jsx
- src/panel_material_ui/widgets/Checkbox.jsx
- src/panel_material_ui/widgets/ColorPicker.jsx
- src/panel_material_ui/widgets/CrossSelector.jsx
- src/panel_material_ui/widgets/DateTimePicker.jsx
- src/panel_material_ui/widgets/MultiSelect.jsx
- src/panel_material_ui/widgets/NumberInput.jsx
- src/panel_material_ui/widgets/PasswordField.jsx
- src/panel_material_ui/widgets/RadioGroup.jsx
- src/panel_material_ui/widgets/Rating.jsx
- src/panel_material_ui/widgets/Select.jsx
- src/panel_material_ui/widgets/Slider.jsx
- src/panel_material_ui/widgets/Switch.jsx
- src/panel_material_ui/widgets/TextField.jsx
- src/panel_material_ui/widgets/TimePicker.jsx
Fixes https://github.com/panel-extensions/panel-material-ui/issues/426
Requires: https://github.com/holoviz/panel/pull/8140
> Portal tooltips into Page root

- src/panel_material_ui/widgets/List.jsx
> Add border to active MenuList item

- examples/reference/indicators/CircularProgress.ipynb
- examples/reference/indicators/LinearProgress.ipynb
- examples/reference/layouts/Tabs.ipynb
- examples/reference/menus/Breadcrumbs.ipynb
- examples/reference/menus/MenuList.ipynb
- examples/reference/menus/MenuToggle.ipynb
- examples/reference/menus/Pagination.ipynb
- examples/reference/menus/SpeedDial.ipynb
- examples/reference/menus/SplitButton.ipynb
- examples/reference/page/ThemeToggle.ipynb
- examples/reference/panes/Chip.ipynb
- examples/reference/panes/Typography.ipynb
- examples/reference/widgets/Button.ipynb
- examples/reference/widgets/CheckButtonGroup.ipynb
- examples/reference/widgets/CrossSelector.ipynb
- examples/reference/widgets/Fab.ipynb
- examples/reference/widgets/FileDownload.ipynb
- examples/reference/widgets/FloatInput.ipynb
- examples/reference/widgets/LiteralInput.ipynb
- examples/reference/widgets/MultiChoice.ipynb
- examples/reference/widgets/PasswordInput.ipynb
- examples/reference/widgets/RadioBoxGroup.ipynb
- examples/reference/widgets/RadioButtonGroup.ipynb
- examples/reference/widgets/Rating.ipynb
- examples/reference/widgets/Select.ipynb
- examples/reference/widgets/TextAreaInput.ipynb
- examples/reference/widgets/TextInput.ipynb
- examples/reference/widgets/ToggleIcon.ipynb
Fixes https://github.com/panel-extensions/panel-material-ui/issues/318
> Align documentation of color variants

- src/panel_material_ui/chat/ChatArea.jsx
- src/panel_material_ui/chat/ChatMessage.jsx
- Reduce size of ChatMessage loading indicator
- Alignment tweaks ChatArea
> Minor Chat tweaks

- src/panel_material_ui/chat/input.py
Otherwise send event is not triggered.
> Trigger send event if sending empty message with uploaded files

- src/panel_material_ui/widgets/FileInput.jsx
- src/panel_material_ui/widgets/input.py
Very much vibe coded...
https://github.com/user-attachments/assets/d05c486c-dde7-4441-88e8-3110fcbf2e1a
``` python
import panel as pn
from panel_material_ui.widgets import FileInput
pn.extension()
file_input = FileInput(label="Upload File", accept=".txt,.csv,.json", multiple=True)
file_input.servable()
```
> enh: Improve FileInput

- src/panel_material_ui/widgets/Button.jsx
Aligns the icon size logic with other components, such as IconButton.
> Align Button icon_size
